server:
  port: 8765
spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 2.0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
          filters:
            - AuthenticationFilter
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true