server:
  port: 0
spring:
  application:
    name: service-a
  sleuth:
    sampler:
      probability: 2.0
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
    register-with-eureka: true
    fetch-registry: false
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}