server:
  port: 8888

spring:
  application:
    name: config-server
  sleuth:
    sampler:
      probability: 2.0
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KirillKuznets0v/eureka-config
          search-paths:
            - "/{application}/{profile}"
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}